platform :ios do
  lane :distribute do
      setup_ci if ENV["CI"]

      resign(
        ipa: ENV["IPA_PATH"],
        signing_identity: ENV["SIGNING_IDENTITY"],
        provisioning_profile: ENV["PROVISIONING_PROFILE"],
      )

      release = firebase_app_distribution(
          app: ENV["FIREBASE_APP_ID"],
          service_credentials_file: "gc_keys.json",
      )
  end
end