platform :ios do
  lane :distribute do
      setup_ci

      match(readonly: true)

      resign(
        ipa: ENV["IPA_PATH"],
        signing_identity: ENV["SIGNING_IDENTITY"],
        provisioning_profile: {
          "*" => ENV["HOME"] + "/Library/MobileDevice/Provisioning Profiles/" + ENV["PROFILE_UUID"] + ".mobileprovision"
        },
        display_name: "uYouPlusExtra"
      )

      release = firebase_app_distribution(
          app: ENV["FIREBASE_APP_ID"],
          service_credentials_file: "gc_keys.json",
      )
  end
end