name: Distribution

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - distribute

jobs:
  distribute:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch IPA
        env:
          GH_TOKEN: ${{ github.token }}
        run: cat latest | gh release download $1 -R arichorn/uYouPlusExtra -p "*.ipa"
      - name: Retrieve Firebase App Distribution Service Account Key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" | base64 -d > gc_keys.json
      - name: Fastlane
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          GC_BUCKET_NAME: ${{ secrets.GC_BUCKET_NAME }}
          BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
        run: |
          bundle install
          bundle exec fastlane match --readonly > match
          cat match
          export IPA_PATH=$(find *.ipa)
          export SIGNING_IDENTITY=$(cat match | grep "Certificate Name" | cut -d "|" -f 4 | xargs)
          export PROFILE_UUID=$(cat match | grep "Profile UUID" | cut -d "|" -f 4 | xargs)
          bundle exec fastlane ios distribute
