name: Distribution

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - distribute

jobs:
  distribute:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch IPA
        env:
          GH_TOKEN: ${{ github.token }}
        run: echo latest | gh release download $1 -R arichorn/uYouPlusExtra -p "*.ipa"
      - name: Retrieve Firebase App Distribution Service Account Key
        run: echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }} > gc_keys.json
      - name: Fastlane
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          fastlane match --readonly > match
          export IPA_PATH=$(find *.ipa)
          export SIGNING_IDENTITY=$(cat match | grep "Signing Identity" | cut -d "'" -f 2)
          fastlane distribute
