name: Version Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch latest release tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release view --repo arichorn/uYouEnhanced --json tagName -q .tagName > latest
      - name: Commit if changed
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update latest version
      - name: Trigger distribution
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: distribute
