on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  check-version:
    name: Version Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh release view --repo arichorn/uYouPlusExtra --json tagName -q .tagName > latest
      - uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Update latest version
